spring.application.name=bist-portfolio-management


spring.datasource.url=jdbc:postgresql://localhost:5432/${POSTGRES_DB}
spring.datasource.username=${POSTGRES_USER}
spring.datasource.password=${POSTGRES_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Port
server.port=8080

spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always

# JWT
jwt.secret=${JWT_SECRET}
jwt.expiration=86400000

# Stock Price Provider - Yahoo Finance (@Primary)
yahoo.finance.base-url=https://query1.finance.yahoo.com/v8/finance/chart

# Stock Price Provider - BigPara (fallback)
bigpara.base-url=https://bigpara.hurriyet.com.tr/api/v1/borsa/hisseyuzeysel

# Scheduler Settings
scheduler.stock-price.request-delay-ms=1000

# Disable scheduling in test profile
spring.task.scheduling.enabled=false